version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: seat_backend
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: seat_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: seat_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: seat_db
    environment:
      POSTGRES_DB: seatdb
      POSTGRES_USER: seatuser
      POSTGRES_PASSWORD: seatpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
