# Generated by Django 5.2.4 on 2025-07-06 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'event_time', 'venue__name'], 'verbose_name': '場次', 'verbose_name_plural': '場次'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'seat__row', 'seat__column'], 'verbose_name': '訂單項', 'verbose_name_plural': '訂單項'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['event', 'row', 'column'], 'verbose_name': '座位', 'verbose_name_plural': '座位'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': '場地', 'verbose_name_plural': '場地'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='場次描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='場次名稱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.event', verbose_name='所屬場次'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='訂單號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', '已登記'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='column',
            field=models.CharField(max_length=10, verbose_name='座位號'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='locked_by_session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='由會話鎖定'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='鎖定至'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='座位價格'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', '可選'), ('locked', '鎖定中'), ('registered', '已登記'), ('cancelled', '已取消')], default='available', max_length=20, verbose_name='座位狀態'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='總座位數'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='layout_data',
            field=models.JSONField(blank=True, help_text='JSON格式的座位佈局信息，例如區域劃分、排數、座位數等。', null=True, verbose_name='座位佈局資料'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='場地名稱'),
        ),
    ]
