# Generated by Django 5.2.4 on 2025-07-06 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_event_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='base_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='基本票價'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='座位價格'),
        ),
    ]
